namespace SystemOptimizer.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemOptimizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string P1_Title => ResourceManager.GetString("P1_Title", resourceCulture);
        public static string P1_Desc => ResourceManager.GetString("P1_Desc", resourceCulture);
        public static string P2_Title => ResourceManager.GetString("P2_Title", resourceCulture);
        public static string P2_Desc => ResourceManager.GetString("P2_Desc", resourceCulture);
        public static string P3_Title => ResourceManager.GetString("P3_Title", resourceCulture);
        public static string P3_Desc => ResourceManager.GetString("P3_Desc", resourceCulture);
        public static string P4_Title => ResourceManager.GetString("P4_Title", resourceCulture);
        public static string P4_Desc => ResourceManager.GetString("P4_Desc", resourceCulture);
        public static string P5_Title => ResourceManager.GetString("P5_Title", resourceCulture);
        public static string P5_Desc => ResourceManager.GetString("P5_Desc", resourceCulture);
        public static string P6_Title => ResourceManager.GetString("P6_Title", resourceCulture);
        public static string P6_Desc => ResourceManager.GetString("P6_Desc", resourceCulture);
        public static string P7_Title => ResourceManager.GetString("P7_Title", resourceCulture);
        public static string P7_Desc => ResourceManager.GetString("P7_Desc", resourceCulture);

        public static string PF1_Title => ResourceManager.GetString("PF1_Title", resourceCulture);
        public static string PF1_Desc => ResourceManager.GetString("PF1_Desc", resourceCulture);
        public static string PF2_Title => ResourceManager.GetString("PF2_Title", resourceCulture);
        public static string PF2_Desc => ResourceManager.GetString("PF2_Desc", resourceCulture);
        public static string PF3_Title => ResourceManager.GetString("PF3_Title", resourceCulture);
        public static string PF3_Desc => ResourceManager.GetString("PF3_Desc", resourceCulture);
        public static string PF5_Title => ResourceManager.GetString("PF5_Title", resourceCulture);
        public static string PF5_Desc => ResourceManager.GetString("PF5_Desc", resourceCulture);
        public static string PF6_Title => ResourceManager.GetString("PF6_Title", resourceCulture);
        public static string PF6_Desc => ResourceManager.GetString("PF6_Desc", resourceCulture);
        public static string PF7_Title => ResourceManager.GetString("PF7_Title", resourceCulture);
        public static string PF7_Desc => ResourceManager.GetString("PF7_Desc", resourceCulture);
        public static string PF8_Title => ResourceManager.GetString("PF8_Title", resourceCulture);
        public static string PF8_Desc => ResourceManager.GetString("PF8_Desc", resourceCulture);
        public static string PF9_Title => ResourceManager.GetString("PF9_Title", resourceCulture);
        public static string PF9_Desc => ResourceManager.GetString("PF9_Desc", resourceCulture);

        public static string N1_Title => ResourceManager.GetString("N1_Title", resourceCulture);
        public static string N1_Desc => ResourceManager.GetString("N1_Desc", resourceCulture);
        public static string N2_Title => ResourceManager.GetString("N2_Title", resourceCulture);
        public static string N2_Desc => ResourceManager.GetString("N2_Desc", resourceCulture);
        public static string N3_Title => ResourceManager.GetString("N3_Title", resourceCulture);
        public static string N3_Desc => ResourceManager.GetString("N3_Desc", resourceCulture);
        public static string N4_Title => ResourceManager.GetString("N4_Title", resourceCulture);
        public static string N4_Desc => ResourceManager.GetString("N4_Desc", resourceCulture);
        public static string N5_Title => ResourceManager.GetString("N5_Title", resourceCulture);
        public static string N5_Desc => ResourceManager.GetString("N5_Desc", resourceCulture);

        public static string S1_Title => ResourceManager.GetString("S1_Title", resourceCulture);
        public static string S1_Desc => ResourceManager.GetString("S1_Desc", resourceCulture);
        public static string S2_Title => ResourceManager.GetString("S2_Title", resourceCulture);
        public static string S2_Desc => ResourceManager.GetString("S2_Desc", resourceCulture);

        public static string A1_Title => ResourceManager.GetString("A1_Title", resourceCulture);
        public static string A1_Desc => ResourceManager.GetString("A1_Desc", resourceCulture);
        public static string A2_Title => ResourceManager.GetString("A2_Title", resourceCulture);
        public static string A2_Desc => ResourceManager.GetString("A2_Desc", resourceCulture);
        public static string A3_Title => ResourceManager.GetString("A3_Title", resourceCulture);
        public static string A3_Desc => ResourceManager.GetString("A3_Desc", resourceCulture);

        public static string SE1_Title => ResourceManager.GetString("SE1_Title", resourceCulture);
        public static string SE1_Desc => ResourceManager.GetString("SE1_Desc", resourceCulture);
        public static string SE2_Title => ResourceManager.GetString("SE2_Title", resourceCulture);
        public static string SE2_Desc => ResourceManager.GetString("SE2_Desc", resourceCulture);

        public static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture);
        public static string Settings_General => ResourceManager.GetString("Settings_General", resourceCulture);
        public static string Settings_Appearance => ResourceManager.GetString("Settings_Appearance", resourceCulture);
        public static string Settings_ThemeDesc => ResourceManager.GetString("Settings_ThemeDesc", resourceCulture);
        public static string Settings_Language => ResourceManager.GetString("Settings_Language", resourceCulture);
        public static string Settings_LanguageDesc => ResourceManager.GetString("Settings_LanguageDesc", resourceCulture);
        public static string Settings_Behavior => ResourceManager.GetString("Settings_Behavior", resourceCulture);
        public static string Settings_Persistence => ResourceManager.GetString("Settings_Persistence", resourceCulture);
        public static string Settings_PersistenceDesc => ResourceManager.GetString("Settings_PersistenceDesc", resourceCulture);
        public static string Settings_KeepInstalled => ResourceManager.GetString("Settings_KeepInstalled", resourceCulture);
        public static string Settings_KeepInstalledDesc => ResourceManager.GetString("Settings_KeepInstalledDesc", resourceCulture);
        public static string Theme_System => ResourceManager.GetString("Theme_System", resourceCulture);
        public static string Theme_Light => ResourceManager.GetString("Theme_Light", resourceCulture);
        public static string Theme_Dark => ResourceManager.GetString("Theme_Dark", resourceCulture);
        public static string Msg_RestartRequired => ResourceManager.GetString("Msg_RestartRequired", resourceCulture);
        public static string Msg_RestartTitle => ResourceManager.GetString("Msg_RestartTitle", resourceCulture);

        // Propriedades adicionadas manualmente para corrigir erro MC3011
        public static string Nav_Privacy => ResourceManager.GetString("Nav_Privacy", resourceCulture);
        public static string Nav_Performance => ResourceManager.GetString("Nav_Performance", resourceCulture);
        public static string Nav_Network => ResourceManager.GetString("Nav_Network", resourceCulture);
        public static string Nav_Security => ResourceManager.GetString("Nav_Security", resourceCulture);
        public static string Nav_Visual => ResourceManager.GetString("Nav_Visual", resourceCulture);
        public static string Nav_Tweaks => ResourceManager.GetString("Nav_Tweaks", resourceCulture);
        public static string Nav_Cleanup => ResourceManager.GetString("Nav_Cleanup", resourceCulture);
        public static string Status_Applying => ResourceManager.GetString("Status_Applying", resourceCulture);
        public static string Status_Loading => ResourceManager.GetString("Status_Loading", resourceCulture);
        
        // Novas propriedades (Existentes no código anterior)
        public static string Btn_Apply => ResourceManager.GetString("Btn_Apply", resourceCulture);
        public static string Btn_Restore => ResourceManager.GetString("Btn_Restore", resourceCulture);
        public static string Btn_RunCleanup => ResourceManager.GetString("Btn_RunCleanup", resourceCulture);
        
        public static string Status_Optimized => ResourceManager.GetString("Status_Optimized", resourceCulture);
        public static string Status_Default => ResourceManager.GetString("Status_Default", resourceCulture);
        public static string Status_Modified => ResourceManager.GetString("Status_Modified", resourceCulture);
        public static string Status_Unknown => ResourceManager.GetString("Status_Unknown", resourceCulture);
        public static string Status_Undefined => ResourceManager.GetString("Status_Undefined", resourceCulture);

        public static string Cleanup_Title => ResourceManager.GetString("Cleanup_Title", resourceCulture);
        public static string Cleanup_CacheTitle => ResourceManager.GetString("Cleanup_CacheTitle", resourceCulture);
        public static string Cleanup_CacheDesc => ResourceManager.GetString("Cleanup_CacheDesc", resourceCulture);
        public static string Cleanup_LogTitle => ResourceManager.GetString("Cleanup_LogTitle", resourceCulture);

        public static string Log_Starting => ResourceManager.GetString("Log_Starting", resourceCulture);
        public static string Log_Finished => ResourceManager.GetString("Log_Finished", resourceCulture);
        public static string Log_DNS => ResourceManager.GetString("Log_DNS", resourceCulture);
        public static string Log_Removed => ResourceManager.GetString("Log_Removed", resourceCulture);
        public static string Log_Clean => ResourceManager.GetString("Log_Clean", resourceCulture);
        public static string Log_WUServicesStopped => ResourceManager.GetString("Log_WUServicesStopped", resourceCulture);
        public static string Log_WUServicesRestarted => ResourceManager.GetString("Log_WUServicesRestarted", resourceCulture);
        public static string Log_WUError => ResourceManager.GetString("Log_WUError", resourceCulture);
        public static string Log_WUFailStop => ResourceManager.GetString("Log_WUFailStop", resourceCulture);

        public static string Msg_SuccessTitle => ResourceManager.GetString("Msg_SuccessTitle", resourceCulture);
        public static string Msg_ResultTitle => ResourceManager.GetString("Msg_ResultTitle", resourceCulture);
        public static string Msg_Applied => ResourceManager.GetString("Msg_Applied", resourceCulture);
        public static string Msg_Restored => ResourceManager.GetString("Msg_Restored", resourceCulture);
        public static string Msg_RebootNeeded => ResourceManager.GetString("Msg_RebootNeeded", resourceCulture);
        public static string Msg_CompletedWithErrors => ResourceManager.GetString("Msg_CompletedWithErrors", resourceCulture);
        public static string Msg_ErrorTitle => ResourceManager.GetString("Msg_ErrorTitle", resourceCulture);
        public static string Msg_InitFail => ResourceManager.GetString("Msg_InitFail", resourceCulture);
        
        public static string App_Title => ResourceManager.GetString("App_Title", resourceCulture);

        // --- ADICIONADO AGORA: Propriedades para a Página de Pesquisa ---
        // Estas propriedades faltavam no Designer.cs e causavam o erro de compilação.
        
        public static string Nav_Search => ResourceManager.GetString("Nav_Search", resourceCulture);
        public static string S_1_Title_New => ResourceManager.GetString("S_1_Title", resourceCulture); // Atenção: S_1 já existe acima para "Show Extensions". 
        // ERRO IDENTIFICADO: As chaves S_1, S_2 já existem para "Security".
        // Vamos usar as chaves corretas definidas no TweakService: S_1_Title (Resources.resx) vs S1_Title (Security)
        
        // CORREÇÃO:
        // No TweakService.cs (Search), usamos: Resources.S_1_Title (com underline)
        // No Resources.resx anterior, definimos: <data name="S_1_Title"...>
        // No Resources.Designer.cs existente, temos S1_Title (sem underline) para SecurityPage.
        
        public static string S_1_Title => ResourceManager.GetString("S_1_Title", resourceCulture);
        public static string S_1_Desc => ResourceManager.GetString("S_1_Desc", resourceCulture);
        
        public static string S_2_Title => ResourceManager.GetString("S_2_Title", resourceCulture);
        public static string S_2_Desc => ResourceManager.GetString("S_2_Desc", resourceCulture);
        
        public static string S_3_Title => ResourceManager.GetString("S_3_Title", resourceCulture);
        public static string S_3_Desc => ResourceManager.GetString("S_3_Desc", resourceCulture);
    }
}
